### ISSUE TITLE
Track detection not working properly on some discs

### ISSUE THREAD

**Issue by davidfuhry** [digital-organology/music-box-discs#13]
On some discs the track detection falsely classifies some notes.

These errors seem to be clustered in some regions rather than beeing random.

E.g.:

![tracks](https://user-images.githubusercontent.com/13850910/112228484-ab4a6e00-8c31-11eb-8d30-dc897d287567.png)

**Comment by robebe** [comment]
Trying some different clustering algorithms for track detection. Spectral Clustering, Agglomerative Clustering and DBSCAN seem to be a good option - for DBSCAN (epsilon=5) we get the same number of clusters as we do with MeanShift (bandwidth=8). However problems with track detection on test_img3.jpg persist:

![rmt3](https://user-images.githubusercontent.com/32611704/114575834-dcd7b780-9c7a-11eb-997c-33d2b7105160.jpg)

**Comment by robebe** [comment]
Trying some different clustering algorithms for track detection. Spectral Clustering, Agglomerative Clustering and DBSCAN seem to be a good option - for DBSCAN (epsilon=5) we get the same number of clusters as we do with MeanShift (bandwidth=8). However problems with track detection on test_img3.jpg persist:

![rmt3](https://user-images.githubusercontent.com/32611704/114575834-dcd7b780-9c7a-11eb-997c-33d2b7105160.jpg)

**Comment by robebe** [comment]
error was in color assignment -> see dienstagsbranch merge into main
