### ISSUE TITLE
Fix edge detection

### ISSUE THREAD

**Issue by davidfuhry** [digital-organology/music-box-discs#16]
Images preprocessed with a strong reduction in brightness and contrast turned to 11 (figuratively) seem to produce the most usable images for further processing, e.g.:

![test_2_80_100](https://user-images.githubusercontent.com/13850910/113738442-2ebe9180-96ff-11eb-9604-43aba80d4e19.JPG)
 
However this seems to interfere with the quality of the edge detection currently used. We see results such as these:

![shapes_2_80_100](https://user-images.githubusercontent.com/13850910/113738665-62012080-96ff-11eb-9e51-4e0901905704.png)

Interestingly the problematic areas are clustered on the left side of the disc. As the preprocessed image is pretty much the ideal image for our purposes this shouldn't be to complex an issue to tackle, however just playing around with the threshold parameters of the canny algorithm did not yield any usable results.

**Comment by davidfuhry** [comment]
Using ImageMagicks EdgeIn method on the preprocessed image yields almost perfect results:

![result](https://user-images.githubusercontent.com/13850910/113739268-ea7fc100-96ff-11eb-92da-7819cb8eb67d.png)

This is documented [here](https://legacy.imagemagick.org/Usage/morphology/#edgein). I was not able to find an OpenCV equivalent as of now.

**Comment by davidfuhry** [comment]
The kind of preprocessing used might require #17 to be implemented to prevent errors.

**Comment by robebe** [comment]
We can create a similar results via:
_, thresh = cv2.threshold(gray, 180, 255, cv2.THRESH_BINARY)

![threshold_blackwhite](https://user-images.githubusercontent.com/32611704/114005705-17e38080-9860-11eb-8aa9-2689daf0e30b.jpg)

with some minor problems at aroud 6.30 o'clock:
![thresh_shapes](https://user-images.githubusercontent.com/32611704/114005870-41041100-9860-11eb-98b3-1c8de4dd4c14.JPG)

![thresh_tracks](https://user-images.githubusercontent.com/32611704/114005858-3fd2e400-9860-11eb-9c7b-e1883a08323d.JPG)

**Comment by davidfuhry** [comment]
That looks great!

How did you preprocess the image? When applying to the one posted atop (and doing the thresholding prior to bluring and canny detection) I still get rather messy results:

![shapes_1_80_100](https://user-images.githubusercontent.com/13850910/114158255-c8b35380-9924-11eb-8e6b-3decc62a10ff.png)

**Comment by robebe** [comment]
Just pushed the changes to dienstagsbranch. The entire preprocessing of colors etc is done [here](https://github.com/digital-organology/music-box-discs/blob/0e899d8456eb72731a099b75b58615b20a650007/musicbox/helpers.py#L30)
which results in the following intermediate picture for track and edge detection (input image DSC04288.jpg):
![processed_picture_tmp](https://user-images.githubusercontent.com/32611704/114374113-96ebf800-9b83-11eb-8c9e-898046cd7744.jpg)

**Comment by robebe** [comment]
if we scale down contrast with factor 0.5 the shape detection seems to produce more fine-grained results (e.g. labeling the crack at ~6.30pm as two different shapes)
