### ISSUE TITLE
Include preprocessing in python script

### ISSUE THREAD

**Issue by davidfuhry** [digital-organology/music-box-discs#9]
We currently preprocess the images using ImageMagick and the following command:

```
convert image.JPG -brightness-contrast -60x40 image_out.JPG
```

We should:

* Do a little more work on finding good parameters
* Include this in the python script

**Comment by davidfuhry** [comment]
So I seem to be too stupid to implemet this using opencv, when trying approaches liek suggested in this [SO question](https://stackoverflow.com/questions/32609098/how-to-fast-change-image-brightness-with-python-opencv) i get results that look like this:

![not_good](https://user-images.githubusercontent.com/13850910/112154039-2edd6e00-8be4-11eb-9543-5b4c582e7c0e.png)

As the python bindings to ImageMagick seem to be somewhat a mess and would also add a dependency to a local ImageMagick installation my suggestion would be to just batch preprocess the images beforehand using imagemagick unless someone else wants to take a look at this. (@Raubwurst @robebe)

We could possibly use Pillow, which has a much higher level API for changing brightness and contrast, but that would involve some data conversion and add another library dependency.

**Comment by davidfuhry** [comment]
This still produces some rather crude output for me when used with a grayscale picture eg. `test_1.jpg`:

```{python}
picture = cv2.imread("data/test_images/test_1.jpg", cv2.IMREAD_GRAYSCALE)
val = 20
brighter_picture = np.where((255 - picture) < val, 255, picture + val)
contrast_picture = brighter_picture * 1.2
```

results in:

![image](https://user-images.githubusercontent.com/13850910/114159697-593e6380-9926-11eb-8f78-a5bc0fc1df7f.png)

While not producing an image at all with rgb images. Or am I applying this wrong?

**Comment by robebe** [comment]
I probably got mixed up with the numbers here. contrast to 0.2 and brightness to 20.
Although I can't reproduce the funny yellow and blue coloring 🖌️
